version: "2"
services:
  nginx:
    image: "nginx"
    volumes:
      - ./conf:/etc/nginx/conf.d
    ports:
      - "443:443"
    links:
      - "node"
  node:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - "3000"
    command: "npm run json-server"
